### ISSUE TITLE
Possible EventEmitter memory leak detected in tests

### ISSUE THREAD

**Issue by macklinu** [JasonEtco/actions-toolkit#56]
Running `npm test` will log the following warning:

```
(node:42520) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

This was discussed in #54 but can be investigated as its own issue.

EDIT: Was able to get a stack trace by running `node --trace-warnings node_modules/.bin/jest`:

```
PASS tests/exit.test.ts
PASS tests/context.test.ts
PASS tests/store.test.ts
(node:16225) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:243:17)
    at process.addListener (events.js:259:10)
    at new Store (/Users/macklinu/Documents/GitHub/actions-toolkit/src/store.ts:47:13)
    at new Toolkit (/Users/macklinu/Documents/GitHub/actions-toolkit/src/index.ts:79:18)
    at Object.<anonymous> (/Users/macklinu/Documents/GitHub/actions-toolkit/tests/index.test.ts:11:15)
    at Object.asyncJestLifecycle (/Users/macklinu/Documents/GitHub/actions-toolkit/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:53:37)
    at resolve (/Users/macklinu/Documents/GitHub/actions-toolkit/node_modules/jest-jasmine2/build/queueRunner.js:41:12)
    at new Promise (<anonymous>)
    at mapper (/Users/macklinu/Documents/GitHub/actions-toolkit/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/Users/macklinu/Documents/GitHub/actions-toolkit/node_modules/jest-jasmine2/build/queueRunner.js:71:41)
PASS tests/index.test.ts

Test Suites: 4 passed, 4 total
Tests:       39 passed, 39 total
Snapshots:   13 passed, 13 total
Time:        2.508s
Ran all test suites.
```

Issue looks to be with this exit handler:

https://github.com/JasonEtco/actions-toolkit/blob/6e3e542602c530f7f8e154b1af3a4d47a0d8719d/src/store.ts#L47-L51

**Comment by JasonEtco** [comment]
Thanks for opening @macklinu - I've updated the title of this issue to reflect that the memory leak is only in tests, since its caused by repeated calls to `.on()` in tests.
